'use client';
import {useMemo,useState} from 'react';
import {Network,Plus,Minus,RotateCcw,ChevronDown,ChevronRight,Users,Shield,UserRound,Building2} from 'lucide-react';
import {Entry,Relation,activeRelation,imageUrl} from '@/lib/model';
import {Choice,Field} from './controls';
export function KindIcon({kind,size=18}:{kind:Entry['kind'],size?:number}){const Icon=kind==='Person'?UserRound:kind==='Organization'?Building2:kind==='Faction'?Users:Shield;return <Icon size={size}/>}
export default function Tree({entries,onSelect,onNew,manage}:{entries:Entry[],onSelect:(entry:Entry)=>void,onNew:()=>void,manage:boolean}){
 const [root,setRoot]=useState('all'),[date,setDate]=useState(''),[zoom,setZoom]=useState(1),[collapsed,setCollapsed]=useState<Set<string>>(new Set());
 const graph=useMemo(()=>{const ids=new Set(entries.map(e=>e.id));const children=new Map<string,{entry:Entry,relation:Relation}[]>();const roots:Entry[]=[];for(const e of entries){const rels=e.relations.filter(r=>ids.has(r.parentId)&&activeRelation(r,date));if(!rels.length)roots.push(e);for(const r of rels)children.set(r.parentId,[...(children.get(r.parentId)||[]),{entry:e,relation:r}])}return{children,roots}},[entries,date]);
 const roots=root==='all'?graph.roots:entries.filter(e=>e.id===root);
 const toggle=(id:string)=>setCollapsed(prev=>{const n=new Set(prev);n.has(id)?n.delete(id):n.add(id);return n});
 const render=(entry:Entry,relation?:Relation,path:string[]=[])=>{if(path.includes(entry.id))return null;const children=graph.children.get(entry.id)||[];return <li key={relation?.id||entry.id}><div className="tree-node-wrap">{relation&&<div className="edge-label" title={relation.note}>{relation.role}<span className={'certainty '+relation.certainty.toLowerCase()}>{relation.certainty}</span></div>}<button className="tree-node" onClick={()=>onSelect(entry)}><span className={'node-portrait '+(entry.images[0]?'has-image':'')}>{entry.images[0]?<img src={imageUrl(entry.images[0].key)} alt=""/>:<KindIcon kind={entry.kind} size={22}/>}</span><span><small>{entry.kind}{entry.status==='Draft'?' · Draft':''}</small><strong>{entry.name}</strong>{entry.aliases&&<em>{entry.aliases}</em>}</span></button>{children.length>0&&<button className="tree-collapse" aria-label={`${collapsed.has(entry.id)?'Expand':'Collapse'} ${entry.name}`} aria-expanded={!collapsed.has(entry.id)} onClick={()=>toggle(entry.id)}>{collapsed.has(entry.id)?<ChevronRight size={14}/>:<ChevronDown size={14}/>}<span>{children.length}</span></button>}</div>{children.length>0&&!collapsed.has(entry.id)&&<ul>{children.map(c=>render(c.entry,c.relation,[...path,entry.id]))}</ul>}</li>};
 return <section><div className="tree-toolbar"><Choice label="Explore a branch" value={root} options={[{value:'all',label:'All organizations & people'},...entries.map(e=>({value:e.id,label:e.name}))]} onChange={setRoot}/><Field label="Relationship date (optional)" type="date" value={date} onChange={setDate}/><div className="zoom-controls"><button className="icon-button" aria-label="Zoom out" disabled={zoom<=.6} onClick={()=>setZoom(z=>Math.max(.6,z-.1))}><Minus size={16}/></button><span>{Math.round(zoom*100)}%</span><button className="icon-button" aria-label="Zoom in" disabled={zoom>=1.5} onClick={()=>setZoom(z=>Math.min(1.5,z+.1))}><Plus size={16}/></button><button className="icon-button" aria-label="Reset tree view" onClick={()=>{setZoom(1);setCollapsed(new Set());setDate('');setRoot('all')}}><RotateCcw size={16}/></button></div></div>{entries.length===0?<div className="archive-empty tree-empty"><div className="archive-symbol"><Network size={36} strokeWidth={1}/></div><h2>Connections give history its shape.</h2><p>{manage?'Create an organization, then link people, factions, and armed wings to it. Your research becomes an interactive tree.':'Organization trees will appear as sourced relationships are added to the archive.'}</p>{manage&&<button className="button primary" onClick={onNew}><Plus size={16}/>Create the first entry</button>}<div className="tree-role-legend"><span>Main boss</span><span>Lieutenant</span><span>Plaza boss</span><span>Faction</span><span>Armed wing</span></div></div>:<><div className="tree-canvas" tabIndex={0} role="region" aria-label="Organization hierarchy. Scroll to explore; select a node to read its profile."><div className="tree-diagram" style={{zoom}}><ul>{roots.map(e=>render(e))}</ul></div></div><p className="tree-note">Select a profile to inspect its sources. Dates filter recorded relationship periods; blank dates mean unknown. This is a research model, not a live command structure.</p></>}</section>
}
